- name: apply the common configuration to all hosts
  hosts: web1,db1
  become: yes

  roles:
  - common

- name: apply httpd and web
  hosts: web1
  become: yes

  roles:
  - httpd
  - web

- name: appy database configuration
  hosts: db1
  become: yes

  roles:
  - mariadb
