- name: install and start ntp using chrony
  hosts: all
  become: yes
  become_user: root
  
  tasks: 
  - name: Set timezone to Asia/Jakarta
    timezone:
      name: Asia/Jakarta
    
  - name: Restart Crond    
    systemd:
      name: crond
      state: restarted

  - name: ensure ntpdate isn't installed
    package:
      name: 'ntpdate'
      state: absent

  - name: install chrony
    package:
      name: chrony
      state: present

  - name: Mask NTP service
    systemd:
      name: ntpd
      enabled: no
      masked: yes
      state: stopped

  - name: Start chronyd service
    service:
      name: chronyd
      state: started

  - name: install chrony.conf
    template:
      src: /home/centos/playbooks/chrony.conf.j2
      dest: /etc/chrony.conf
      owner: root
      group: root
      mode: 0644


  handlers:
    - name: restart chrony
      service:
        name: chronyd
        enabled: yes
        state: restarted
